messages:
  notif-type-not-found: "&cThat notification type has not been found."
  error-message: "&cUh oh! An error has occurred. Check console for more information."
  basic-usage: "&cUsage: /discordnotif <type> [extra information]"
  no-permission: "&cYou do not have permission to execute this command."
  no-permission-notif: "&cError: You have no permission to use this notif."
Hack:
  aliases:
    - hack
    - hacking
    - cheat
    - cheating
  url: https://discordapp.com/api/webhooks/...
  min-args: 1
  usage-message: '&cUsage: /discordnotif Hack <player> <reason> [extra information]'
  success-message: '&eThank you for &creporting&e &a%1%&e!'
  discord-message: |
    %player_name% is reporting: %1% for %2%.
    ```%1-4%```
    ```%4+%```